// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8hEtpOn7wroE9tyze2P3CVf2GIcGN3KE',
    appId: '1:897416495346:web:083d8f2010f97fea64506b',
    messagingSenderId: '897416495346',
    projectId: 'smartfood-iot',
    authDomain: 'smartfood-iot.firebaseapp.com',
    databaseURL: 'https://smartfood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfood-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5erYc67uqV0x48EOOiIWLyaQedmY_e3w',
    appId: '1:897416495346:android:aa49031af5950f6464506b',
    messagingSenderId: '897416495346',
    projectId: 'smartfood-iot',
    databaseURL: 'https://smartfood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfood-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVHLH2Wrs6VwCwSe9hyR3XGoGhlh-Yo3A',
    appId: '1:897416495346:ios:67d8af7c156ffc1364506b',
    messagingSenderId: '897416495346',
    projectId: 'smartfood-iot',
    databaseURL: 'https://smartfood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfood-iot.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVHLH2Wrs6VwCwSe9hyR3XGoGhlh-Yo3A',
    appId: '1:897416495346:ios:67d8af7c156ffc1364506b',
    messagingSenderId: '897416495346',
    projectId: 'smartfood-iot',
    databaseURL: 'https://smartfood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfood-iot.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8hEtpOn7wroE9tyze2P3CVf2GIcGN3KE',
    appId: '1:897416495346:web:6784aa09ff46e70d64506b',
    messagingSenderId: '897416495346',
    projectId: 'smartfood-iot',
    authDomain: 'smartfood-iot.firebaseapp.com',
    databaseURL: 'https://smartfood-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartfood-iot.firebasestorage.app',
  );
}
